### ISSUE TITLE
Adjust space parameters based on newly derived relative abundance values for each STEPPE plant functional type

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#106]
The final step in this milestone is to reset the space parameters for each functional type to the relative abundance of that functional type. For example, 

space c3grass = relabun c3grass = 0.3

**Comment by chaukap** [comment]
@kpalmqui I have a few questions related to functional type mapping. I tagged you in a comment on commit 771fee1, but I thought I should also document it here. 
In my implementation I use the name of the rgroup to determine if it is a shrub, succulent, c3 grass, ect. I am not sure what rgroup names relate to c3 grasses, c4 grasses and trees. Once I have that information I will be able to add it to the code and we should be about done!

**Comment by chaukap** [comment]
Runs have completed on Teton and input files are adjusted correctly.
