### ISSUE TITLE
Populate new space parameters in the correct rgroup.in files in the STEPWAT_DIST folder

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#107]
![image](https://user-images.githubusercontent.com/7769797/50654692-aa976580-0f5b-11e9-8353-9ff2cf13ecc1.png)

**Comment by chaukap** [comment]
rgoup.in files are now generated for each climate scenario, with space rescaled based on the rescaled values and user input.
