### ISSUE TITLE
Readjusted space parameters no longer sum to 1

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#117]
The readjusted space parameters that are calculated from the relative abundance of plant functional types no longer sum to 1. For site 1 under current conditions with the default settings in InputData_Rgroup.csv, the values sum to ~ 0.48. Something is likely going wrong within the code that takes the initial relative abundance values produced from estimate_PotNatVeg_composition and re-partitions themfor STEPPE plant functional types based on the types and their respective space parameters that are provided in inputs in InputData_Rgroup.csv.
@chaukap 

[readjusted.space.xlsx](https://github.com/DrylandEcology/rSFSTEP2/files/2769864/readjusted.space.xlsx)

**Comment by kpalmqui** [comment]
The problem results from generation of relVegAbun within STEPWAT.Wrapper.MAIN_V3.R on line 558. This is not necessary as, we have derived relVegAbund within Vegetation.R. It essentially undoes everything that was implemented in Vegetation.R. 

We need to remove this line and replace all occurrences of "relVegAbund" with the object that is created in Vegetation.R, i.e.:

`res[n_sites, k_scen, ] <- temp_veg[["Rel_Abundance_L0"]]`

**Comment by chaukap** [comment]
I believe commit a6fd7ef solves the problem, and it also documents my rationale. @kpalmqui if you are still running into issues let me know and I'll take another look.

**Comment by chaukap** [comment]
I believe commit a6fd7ef solves the problem, and it also documents my rationale. @kpalmqui if you are still running into issues let me know and I'll take another look.

**Comment by kpalmqui** [comment]
@chaukap Yes - that does seem to have fixed the problem! At least for site 1 under both current and future conditions. Good work.
