### ISSUE TITLE
Error: argument of length 0 in wrapper.code

### ISSUE THREAD

**Issue by chaukap** [DrylandEcology/rSFSTEP2#121]
I did not know this, but in a loop like
```
for(rg in rgroups)
```
rg does not take on the names from rgroups. Therefore
```
names(rg)
```
is returning NULL which causes the error. This can be corrected by changing the loop to 
```
for(rg_index in length(rgroups))
```
and adding 
```
rg <- rgroups[rg_index] 
```
inside the loop. This way rg will have the same name as the corresponding value in rgroups.

**Comment by kpalmqui** [comment]
The above commit 1841d75 has resolved this on my end as well.
