### ISSUE TITLE
WARNING: RGroup succulents : res_avail is Zero and res_required > 0 is occurring when space = 0, but the functional type is still on

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#123]
With dynamic scaling of space based on climate, the warning:

`WARNING: RGroup succulents : res_avail is Zero and res_required > 0`

was occasionally being printed for some sites. Upon closer examination, this warning is being triggered for those functional types whose space parameter is set to 0 based on climate. Essentially, this functional type is assigned no resources, despite being turned on.

Solution: for those functional types whose space parameter is set to 0 based on a given climate scenario, we also need to turn that functional type off in rgroup.in. This is set in the "on" column.

@chaukap how difficult will it be to do this on the fly?

Here is an example logfile and rgroup.in. Note this warning is only being printed for succulents, which is the only FT with space = 0.

[logfile.log](https://github.com/DrylandEcology/rSFSTEP2/files/2824477/logfile.log)

[rgroup.txt](https://github.com/DrylandEcology/rSFSTEP2/files/2824478/rgroup.txt)

**Comment by chaukap** [comment]
This shouldn't be too difficult I'll implement the code today!

**Comment by kpalmqui** [comment]
@chaukap the above commit seems to have resolved the problem on my end. Are you able to confirm? If so, you can close the issue. Thanks!

**Comment by chaukap** [comment]
I can confirm!
