### ISSUE TITLE
climate_veg_scaling runs failing on Teton

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#124]
Some test runs utilizing the climate_veg_scaling and feature_space branches of rSFSTEP2 and STEPWAT2  have failed. These runs were for 100 iterations and 300 years. See the following for the error:

[slurm.txt](https://github.com/DrylandEcology/rSFSTEP2/files/2824537/slurm.txt)

Note: the same runs with 1 iteration and 300 years completed on my local machine. Could this be a memory issue? I requested 128 GB nodes on Teton, which seems like it should be enough....

@chaukap

**Comment by chaukap** [comment]
@kpalmqui This is concerning... `mv: cannot stat ‘bmassavg.csv’: No such file or directory` leads me to believe that STEPWAT never ran, therefore there is no output. I doubt that this is a memory problem, were the correct number of input files generated?

**Comment by kpalmqui** [comment]
@chaukap yes - for some of the sites, the Output folder is empty, so STEPWAT2 never ran. These simulations were all run with three sets of "all/fixed" in the Rgroup input csv file, which is attached. All of the necessary rgroup.in input files in STEPWAT_DIST seem to be there: 3 files for current (fixed 1,2,3) and 12 files for 1 future GCM (3 fixed rgroup inputs*2 RCPs*2 time periods)

Perhaps the wrapper code is not properly set up to deal with multiple "all/fixed" categories?
The strange thing is some sites got farther along than others- for instance Site 1 got through fixed inputs 1 and 2, but failed at 3, while Site 2 never had any output generated. 

Let me know if there are other specific questions I can answer.

**Comment by kpalmqui** [comment]
Update: this was also failing on my local machine. It appears to result from a segfault in R (very rare) from an incompatibility between installed packages and the R version installed. 

A clean install of the latest version of R, along with removal and re-installation of the required packages for rSFSTEP2 seems to have resolved this problem on my local machine.  See: https://stackoverflow.com/questions/49190251/caught-segfault-memory-not-mapped-error-in-r

Solution for Teton: check compatibility of all installed R packages and the R version being utilized.

**Comment by kpalmqui** [comment]
The reason the code is failing on Teton is not the same reason it was failing on my local machine (see above comment). 

The cause of failure on Teton was that the number of individuals for some species exceeded 100, which is the number that is set as the maximum number of individuals allowed per species in the STEPWAT2 ( `MAX_INDIVS_PER_SPP`). This resulted in the program aborting (see below files). I have decreased` eind` ( the max number of individuals that can establish each year) from 20 to 10 and the runs on Teton completed.

This issue is easy to resolve and has three potential solutions:
1) Increase the number of individuals for each species that is allowed in `MAX_INDIVS_PER_SPP`
2) Reduce `eind`, so we are simulating < 100 individuals.
3) a hybrid of both

For most species, we do not want to simulate more than 100 individuals per m2, becasue those are unrealistic densities. However, we will likely want to simulate that many (or more) Bromus tectorum (BRTE) individuals in invaded sites.

@chaukap perhaps increasing `MAX_INDIVS_PER_SPP`, but also reducing eind for the species where individuals should be < 100 is the way to go?

**Comment by chaukap** [comment]
@kpalmqui we could try increasing `MAX_INDIVS_PER_SPP` to something like 120, and reduce `eind` slightly. This would give the program a little more wiggle room without becoming unreasonable. What do you thing?

**Comment by kpalmqui** [comment]
@chaukap I would like to discuss the reasonable max individuals for cheatgrass with Bill, but I will get back to you shortly on what the upper limit of  `MAX_INDIVS_PER_SPP ` should be.

**Comment by kpalmqui** [comment]
Note this issue had been previously documented (but not described well) in the Fire_testing milestone of STEPWAT2:
https://github.com/DrylandEcology/STEPWAT2/issues/108

**Comment by kpalmqui** [comment]
Decision- let's leave MAX_INDIVS_PER_SPP = 100 for now. We use reduce eind/pestab to modify the number of individuals established. 100 individuals per 100/m2 is way too high for perennial grasses. 

We may need to revisit this decision in the future for cheatgrass and we should also consider moving this and related variables into inputs in the future. I will create a new issue for both.

**Comment by kpalmqui** [comment]
This issue has been resolved by adjusting eind downward and climate_veg_scsaling runs are now complete on Teton.
