### ISSUE TITLE
Break generate_stepwat_sites.sh into two shell scripts to reduce upfront user time

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#141]
generate_stepwat_sites.sh has two main purposes:

1. Clone and compile STEPWAT2 and remove unnecessary .c and .h files after compilation.
2. Create the folder structure necessary to run STEPWAT2 in pseudo-parallel for as many sites and scenarios that the user requests.

Everytime I utilize rSFSTEP2 for testing or simulation runs I have to utilize generate_stepwat_sites.sh in a piecemeal fashion because I typically want to make changes to inputs within STEPWAT2 after it is cloned and compiled (1) but before it is copied to create the necessary folder structure (2). As such, I comment out lines 30-44, run generate_stepwat_sites.sh to clone STEPWAT2 and then make my changes. Thereafter I comment out lines 6-28 and run generate_stepwat_sites.sh again to then set up the necessary file structure with my changes incorporated. 

The typical changes include:
1. Updating iterations, years, and seed to 100, 300, 0 within model.in (@chaukap has suggested potentially incorporating this as inputs to rSFSTEP so this step would no longer be necessary)
2. Remove all weath.in files in randomdata, which will be used in simulations if not deleted.

It would be great to break generate_stepwat_sites.sh into two shell scripts to reflect the two main purposes described above, so I (and future users) don't have to do this anymore.

Perhaps appropriate names could be:

cloneSTEPWAT2.sh
generate_rSFSTEP2_structure.sh

@chaukap

**Comment by chaukap** [comment]
@kpalmqui I'm ready to start work on this issue once a branch is created. Did we want to create the branch off of WeatherGeneratorInputFiles_from_rSOILWAT2 or hold off until the weather generator issues are resolved?

**Comment by kpalmqui** [comment]
@chaukap sorry meant to do this yesterday and forgot. Yes, let's create it off WeatherGeneratorInputFiles_from_rSOILWAT2. Thanks! I will still update parameters on this branch once created (the one issue assigned to me).

**Comment by chaukap** [comment]
@kpalmqui It's no trouble, the branch has been created.

**Comment by kpalmqui** [comment]
@chaukap just tested these changes to the shell scripts on my computer and all is working as expected. You can close the issue - thanks!

**Comment by chaukap** [comment]
@kpalmqui Great to hear! I'll close this issue and move on to the rest of the issues in this branch.
