### ISSUE TITLE
Properly handle paths with spaces

### ISSUE THREAD

**Issue by fdpierson** [DrylandEcology/rSFSTEP2#147]
When running rSFSTEP2 from a location where the path has spaces, for example, "~/path name", we get errors involving the cp and mv commands, many of which I believe originate from CallSTEPWAT2.R.

**Comment by kpalmqui** [comment]
@fdpierson is this still a problem within the current workflow you have identified? please update this issue when you can. thanks!

**Comment by fdpierson** [comment]
@kpalmqui I forgot the exact workflow which caused spaces in paths to become an issue. I will look into this.

**Comment by kpalmqui** [comment]
@fdpierson can you please confirm there are actually no problems here and we can close this issue? Many thanks!!
