### ISSUE TITLE
Branch fails when running with Current conditions only.

### ISSUE THREAD

**Issue by chaukap** [DrylandEcology/rSFSTEP2#149]
The problem is on line 628:
```
total_space <- data.frame(relVegAbund[i,,])
```
Where we turn the space vector into a data frame. If we run with `Current` only `data.frame` behaves differently than if we have more than one entry.
* With `Current` only the `data.frame` compresses all of the functional types into one column with 8 rows. Therefore, `names(total_space)` only has one erroneous entry. 
* With more than one GCM `data.frame` creates a column for each functional type, with names(total_space) == the names of the functional types. 

We need a permanent solution that works with any number of climate scenarios. This will require a little experimenting on my part.

@kpalmqui If you need this working immediately, while I look for a permanent solution, I can put a band-aid on this which would check if "Current" is the only climate condition then act accordingly. Once I come up with a permanent  solution I would remove the band-aid.

**Comment by kpalmqui** [comment]
@chaukap thanks for documenting! I have been overcoming this problem by simply running 1 future scenario in addition, despite the fact that my test runs only require current conditions. This has not posed any problems for me thus far and I can continue to do so over the next week or two.

Therefore, I don't think the 'bandaid' is necessary, but I will let you know if that changes.

**Comment by chaukap** [comment]
I have a fix in place. It isn't as eloquent as I would like, but I can't get `data.frame` to behave the way I would like. This fix looks at how many elements are in `climate.conditions` and adjusts `total_space` if there is only one. To "normalize" `total_space` I took the transpose then called `data.frame` again.

Also note that this bug isn't unique to using `Current`. As long as `length(climate.conditions) == 1` this bug would have crashed the program.

**Comment by kpalmqui** [comment]
@chaukap I ran a test run on my computer with current conditions and it completed. However, I am getting some warnings:

![image](https://user-images.githubusercontent.com/7769797/60589962-c9d74a00-9d68-11e9-962c-2dacbefcf476.png)

**Comment by chaukap** [comment]
@kpalmqui I have looked into these warnings and there doesn't seem to be a way to suppress them. Apparently the write.table function thinks it is necessary to let us know every time it adds column names to a file, even though `col.names = !file.exists("total_mort.csv)` ensures that column names are only appended if we are creating a brand new file.

**Comment by kpalmqui** [comment]
@chaukap thanks for looking into this - I guess we can close this issue then. We could potentially re-evaluate this code later to see if another approach is available in case we get annoyed with the warnings.
