### ISSUE TITLE
Space > 0, but rgroup turned off under future conditions

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#157]
I have found a bug in master of rSFSTEP2. When `rescale_space = TRUE`, space parameters are derived based on current or future climate conditions. For a given climate scenario, if `space = 0`, then that rgroup is also turned off (`on/off `set to 0).

This functionality appears to be working under current conditions. However, it is not working under future conditions. Frequently under future conditions, `space` is set to > 0, but the rgroup is turned off.  See here:

rgroup.in file for the site 13 under current conditions (looks good): 

[rgroup.freq.01333.graz.1.41.fixed2.Current.site13.txt](https://github.com/DrylandEcology/rSFSTEP2/files/3574726/rgroup.freq.01333.graz.1.41.fixed2.Current.site13.txt)

rgroup.in file for site 13 under a future scenario (not good): 
[rgroup.freq.01333.graz.1.41.fixed2.hybrid-delta-3mod.d50yrs.RCP45.CanESM2.site13.txt](https://github.com/DrylandEcology/rSFSTEP2/files/3574727/rgroup.freq.01333.graz.1.41.fixed2.hybrid-delta-3mod.d50yrs.RCP45.CanESM2.site13.txt)

I thought this was just a matter of the space being set to 0 whenever it was set to 0 under current conditions, but that doesn't not seem to consistently be the case as exhibited here:

site 11, current:

[rgroup.freq.01333.graz.1.41.fixed2.Current.site11.txt](https://github.com/DrylandEcology/rSFSTEP2/files/3574746/rgroup.freq.01333.graz.1.41.fixed2.Current.site11.txt)

site 11, future:

[rgroup.freq.01333.graz.1.41.fixed2.hybrid-delta-3mod.d90yrs.RCP85.HadGEM2-ES.site11.txt](https://github.com/DrylandEcology/rSFSTEP2/files/3574749/rgroup.freq.01333.graz.1.41.fixed2.hybrid-delta-3mod.d90yrs.RCP85.HadGEM2-ES.site11.txt)

And sometimes the rgroup.in files for the future scenarios are correct (if a group was turned off consistently under both current and future scenarios).

@chaukap @dschlaep

**Comment by dschlaep** [comment]
@kpalmqui I briefly looked at where `on/off` is being set, i.e., lines 696-700 of `Main.R` on the master branch:
```
          #if space equals 0 for this type, we need to set the "on" column to false. This will turn off the type.
          if(rgrp[[y]][2] == 0){
            rgrp[[y]][9] <- 0   # rgrp[[y]][9] is the "on" column
          }
...
```

I see two potential issues:
- `rgrp[[y]][2]` is not an integer, thus testing for exact equality with `==` may be problematic
- not having an `else` clause assumes that the previous value of `on/off` is the correct one

--> this may help?
```
            rgrp[[y]][9] <- if (rgrp[[y]][2] > 0) 1L else 0L
```

**Comment by kpalmqui** [comment]
@dschlaep thanks for responding so quickly! 

When `space `is '0' it is actually set to a 0 not 0.0 in the file, so I don't think that is the problem, but I do think that the lack of an else statement could be contributing...

**Comment by kpalmqui** [comment]
This also seems to have affected c3 perennial grasses, in addition to c4 perennial grasses, and c3 annual grasses.

**Comment by chaukap** [comment]
@dschlaep You were right about the necessity of an else clause. I incorrectly assumed that all rgroups would be "on" by default before space is reassigned and therefore didn't have any functionality in place to turn them "on". I tested commit 5946eb0 on vic sites 4 and 15, which both contained the bug before, and rgroups now turn back on for climate scenarios where space > 0.

**Comment by kpalmqui** [comment]
@chaukap thank you! I will get a set of test runs going this evening on Teton for some additional sites that had this problem and confirm.

**Comment by kpalmqui** [comment]
@chaukap @dschlaep This bug has been resolved on my end. Functional types are being turned off properly when space = 0. Tested for ~40 sites for multiple future scenarios. The output all looks good. 

@chaukap can you open a pull request and assign me as a reviewer? thanks!
