### ISSUE TITLE
Create InputData_GrowingSeason.csv

### ISSUE THREAD

**Issue by chaukap** [DrylandEcology/rSFSTEP2#158]
In order to modify plant phenology based on site and climate we need a rough estimate of the growing season. This estimate should vary across sites.

**Comment by kpalmqui** [comment]
@dschlaep @chaukap 

We now have phenological activity values, biomass, litter, and %live contained within input csvs and passed into rSFSTEP2. We populated these tables with the default values that were being used in sxw_phen.in and sxw_prodv2.in. These same values are being used for every site (but then ultimately scaled based on mean monthly temp).

Do you think it would be wise to add functionality to rSFSTEP2 to also allow the user to specify differ phenological activity values, biomass, litter, and %live values for sxw_phen.in and sxw_prod.v2.in for different sites (i.e. site-specific inputs)? I'm not sure how much we would actually use this functionality, but this would be consistent with the functionality available for species, rgroup, and soil inputs (the user can currently provide the same input values for all sites or site-specific inputs).

**Comment by kpalmqui** [comment]
@dschlaep just following up on this issue - what do you think about my comment above @dschlaep @chaukap

**Comment by dschlaep** [comment]
If we don't have a specific use case now or in the foreseeable future for capabilities that the user can provide specific phenological activity values for different sites, then we could consider to file this as an enhancement issue to be re-visited at a suitable later time and move forward with what we have?

**Comment by kpalmqui** [comment]
thanks @dschlaep I tend to agree. I'll document this idea as a low-priority issue and we can revisit in the future if we need to.

**Comment by kpalmqui** [comment]
resolved by d9db932
