### ISSUE TITLE
Copy the new phen and prod files into STEPWAT2

### ISSUE THREAD

**Issue by chaukap** [DrylandEcology/rSFSTEP2#164]
prior to call ing STEPWAT2 we need to ensure our versions of sxwprod_v2.in and sxwphen.in have replaced the default files.

**Comment by kpalmqui** [comment]
Furthermore, we need to we sure that the specific sxwprod_v2.in and sxwphen.in for each climate scenario (GCM-timeperiod-RCP) are replaced for simulations for current conditions or each GCM-time period-RCP combo.
