### ISSUE TITLE
Create function to compare generated .in files

### ISSUE THREAD

**Issue by chaukap** [DrylandEcology/rSFSTEP2#168]
Currently there is no good way to compare the different RGroup, Soil, and Species files generated by the wrapper. We need to make a standalone function that can read the .in files and output some general information about them. The format of the output should be something like
```
| Greatest difference | Minimum value | Maximum value | standard deviation
```
For each input from each input file type.

**Comment by kpalmqui** [comment]
@chaukap might it be possible to also add some code to generate graphics here?  Simple line plots of month (x-axis) vs. phenological activity (y-axis) would be helpful.

**Comment by kpalmqui** [comment]
@chaukap should we move this to phenology_biomass_scaling, where commits related to these issues are now being implemented?

**Comment by kpalmqui** [comment]
I am re-assigning this issue to phenology_biomass_scaling, as the development branch related to this issue has been incorporated there.

**Comment by kpalmqui** [comment]
@chaukap I believe this issue can now be closed. If you agree, please do so.
