### ISSUE TITLE
Add "Current" black line to all graphics

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#175]
Add a solid black line connecting all values under "Current" conditions to each graphic for phenological activity, biomass, litter, and %live. It is often hard to see which set of points the "Current" points are hiding behind and thus hard to interpet how values are changing from Current to future conditions.

@chaukap

**Comment by chaukap** [comment]
@kpalmqui I added the black line, and also added "Current" to all of the prod files. Let me know if this is what you were looking for!

**Comment by kpalmqui** [comment]
@chaukap this looks good for biomass, litter, and %live, but there aren't any lines for Current conditions for phenological activity.

**Comment by chaukap** [comment]
@kpalmqui That was my mistake, I overlooked the phenology graphics. I just committed f9ea37c which implements the black lines in the phen files.

**Comment by kpalmqui** [comment]
@chaukap many thanks!
