### ISSUE TITLE
Make Figures that show how space is scaled based on current and future climate

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#177]
Space parameters are currently dervied on the fly for each site based on climate conditions. Rather than having to dig through all the rgroup.in files, it would be very helpful to have Figures that for each site and each functional type show the default space parameter, along with space parameters under current and future conditions. One idea is to potentially plot each functional type on a seperate panel within a multi-paneled Figure. Each panel would be a barplot containing the default space parameter for that functional type, along values of space for current conditions and all future conditions. 

@chaukap

**Comment by kpalmqui** [comment]
@chaukap these look good - but the default space values for each STEPPE rgroup are not included here. Would that be possible to add the default space value for a given rgroup to each Figure? I realize for some of these Figures the scaled space values are much smaller than the original value - perhaps we can just add some text here that says "original space = xx", so we don't have to adjust the y-axis?

**Comment by chaukap** [comment]
@kpalmqui I implemented your suggestion by adding a line below the title that states the original value. Let me know what you think!

**Comment by kpalmqui** [comment]
@chaukap I just ran rSFSTEP2 on the latest commit and this looks good! Thanks. I think we are ready to close this issue.
