### ISSUE TITLE
Update README file to reflect new functionality that compares input files generated on the fly

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#181]

**Comment by chaukap** [comment]
@kpalmqui I've added the description. I'll leave this issue up over the weekend to give you a chance to look then close it on Monday.

**Comment by kpalmqui** [comment]
@chaukap see my comment on https://github.com/DrylandEcology/rSFSTEP2/commit/752ec1d3d29e48c6a43ce920af9895374b03932e
