### ISSUE TITLE
Error in scale_phenology(values_to_scale, sw_weatherList, monthly.temperature,  :    object 'n_sites' not found

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#187]
feature_phenology_biomass_scaling fails using master branch of STEPWAT2 and latest commit on rSOILWAT2 due to above error.

**Comment by chaukap** [comment]
I'll get on this right away.

**Comment by chaukap** [comment]
@kpalmqui The bug is resolved. This was a small disordering of commands that caused n_sites to be used before it was declared. Sorry about this!

**Comment by kpalmqui** [comment]
@chaukap no biggie. I'll start my test runs again!

**Comment by kpalmqui** [comment]
@chaukap this bug has been resolved on my end by the above commit, so I am closing this issue.
