### ISSUE TITLE
New panels in phenology/biomass/%live/litter figures that show default monthly temperatures along with monthly temperatures utilized to derive values

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#190]
Monthly temperature is now being used to derive phenological activity values, biomass, %live, and litter within rSFSTEP2 (instead of growing season). We need to add a new panel to all Figures that are generated by compare_files.sh that show:

1. default monthly temperatures in blue (and add this to the legends for both panels so the user knows what the blue line represents)
2. actual monthly temperatures used to estimate phenological activity, biomass, litter, and %live. Each scenario (i.e. current) should be plotted with the same symbols/colors for temperature and the scaled variables.

@chaukap let me know if you have questions. If you could begin with phenological activity and tag me when you think you have the code implemented that would be great.

**Comment by chaukap** [comment]
@kpalmqui I'm about 3/4 done with this issue. I'll wrap it up tomorrow and tag you when I'm done.

**Comment by chaukap** [comment]
@kpalmqui commit 27ad923 should wrap up this issue. If my formatting matches what you were picturing let me know and I'll close this issue.

**Comment by kpalmqui** [comment]
@chaukap the updated figures look great and are very helpful, so this issue is resolved.
