### ISSUE TITLE
Include BVT values (biomass & transpiration) for each RGroup within InputData_Rgroup.csv

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#191]
Within the fg_specificity_sxw branch of STEPWAT2, we now provide specific values of BVT (biomass/transpiration) for each functional type (rgroup) within rgroup.in. We need to add biomass & transpiration as new columns in InputData_Rgroup.csv. 

See: https://github.com/DrylandEcology/STEPWAT2/issues/347

**Comment by chaukap** [comment]
@kpalmqui This milestone is going to conflict heavily with feature_phenology_biomass_scaling, so I was hoping we could hold off until we can that branch merged into master. Alternatively, if it is going to take a while to merge into master we could first merge it into this branch then start development.

**Comment by kpalmqui** [comment]
@chaukap well, here we are a month later and feature_phenology_biomass_scaling is still not resolved. I am wondering if it might be wise to implemented the latter and fold feature_phenology_biomass_scaling into this branch. It would also be really nice to be able to work on the litter issues and provide functional type specific litter values to the scale_phenology function.

Thoughts?
