### ISSUE TITLE
Derived litter fractions and biomass fractions exceed 1.0

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#194]
We are now derving all input values within sxwprod_v2.in dynamically based on the monthly temperature values for a given site-scenario. The parameters in sxwprod_v2.in convert annual STEPPE funcitonal type biomass to monthly SOILWAT functional type biomass, % live, and litter for each year's SOILWAT2 run. 

When looking carefully at the Figures generated for biomass, % live and litter, I noticed that biomass fraction values and litter fraction values are exceeding 1 for some scenarios. This should not happen. While the monthly values do not need to sum to 1.0, any given monthly value cannot exceed 1.0, as these represent percentages. See the description in sxwprod_v2.in and demonstration of the problem here:

![a cool grass_46-52_biomass_graph](https://user-images.githubusercontent.com/7769797/71113857-bccddc00-218b-11ea-93cd-1a5d771a8b6d.png)

![LITTER_46-53_graph](https://user-images.githubusercontent.com/7769797/71113887-cbb48e80-218b-11ea-9fa9-16eb764475d6.png)

@chaukap can you help to resolve this issue by capping all derived values at 1.0? While I did not notice this problem yet for % live, that needs to be capped at 1.0 as well.

**Comment by chaukap** [comment]
@kpalmqui  This issue should be resolved.

**Comment by kpalmqui** [comment]
This issue has been resolved by the above two commits.
