### ISSUE TITLE
Constrain litter, %live, and biomass fractions by the sum of the default fractions

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#197]
@dschlaep and I noticed that litter, %live, and biomass fractions that are derived on the fly based on future monthly temperatures are often quite larger for most months relative to current and default (input) conditions. Biologically, this does not make sense. 

Because the future is warmer, values are increasing in almost every month with few constraints. We believe a logical and realistic initial solution to this problem is to constrain all derived values for each functional type such that their sum across all months is equivalent to the summed monthly default values for that functional type. 

@chaukap let me know if you have any questions.

**Comment by chaukap** [comment]
@kpalmqui Check out the solution I just pushed. I realized that the easiest way to do this was to first normalize the values to sum to 1, like phenology, then multiply each value by the sum of the fractions read in from inputs.

**Comment by kpalmqui** [comment]
@chaukap this looks great! I will test this over the weekend and report back.

**Comment by kpalmqui** [comment]
@chaukap @dschlaep 
The above commit has resolved this issue. The percent live, biomass, and litter fraction Figures look much more reasonable and are more in line with phenological activity now. The large increases from current to future conditions have disappeared. I am happy with these results and therefore I am closing this issue.

Old litter implementation:
![Site5_OLD_LITTER_46-53_graph](https://user-images.githubusercontent.com/7769797/72268811-82bbf280-35f0-11ea-8982-deda1365238e.png)

New litter implementation:
![Site5_NEW_LITTER_46-53_graph](https://user-images.githubusercontent.com/7769797/72268819-88b1d380-35f0-11ea-95a1-bf7c455b851c.png)

Old biomass implementation:
![Site5_OLD_p cool grass_46-52_biomass_graph](https://user-images.githubusercontent.com/7769797/72268832-8ea7b480-35f0-11ea-93ba-18a1b1861df3.png)

New biomass implementation:
![Site5_NEW_p cool grass_46-52_biomass_graph](https://user-images.githubusercontent.com/7769797/72268845-95cec280-35f0-11ea-9e12-9a8d9dd5ace8.png)

**Comment by chaukap** [comment]
@kpalmqui That's great to hear!
