### ISSUE TITLE
Remove scaling of phenological activity values to sum to 1.0

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#202]
@dschlaep determined that phenological activity values do not need to sum to 1.0 for transpired water to be partitioned correctly. In fact, scaling them to 1.0 causes undesirable behavior. See https://github.com/DrylandEcology/STEPWAT2/issues/430 for more explanation.

This issue will remove lines 668-671 in `Main.R` that rescale the phenological activity values coming out of `scale_phenology` to 1.0.

**Comment by chaukap** [comment]
@kpalmqui Should I add a check to make sure that no single phenological value is greater than 1, just in case?

**Comment by kpalmqui** [comment]
@chaukap for the time being, we are going to use the unscaled values with no additional adjustments. So no - you don't need to add a check to ensure that individual phenological activity values =< 1.0.
