### ISSUE TITLE
Create shell scripts to call compareFiles.R on a computing cluster

### ISSUE THREAD

**Issue by chaukap** [DrylandEcology/rSFSTEP2#218]

**Comment by chaukap** [comment]
@kpalmqui I just tested this commit on Teton using some of the DIST directories you generated in your last rSFSTEP2 run. The tasks completed and the output was generated. There is one bug where the `job.txt` file will read "Site noid done!" which I will fix with my next commit.

**Comment by kpalmqui** [comment]
@chaukap thanks for the update! Which folder did you execute this in? 

I ask becasue I ran the shell script last night for all 91 sites in the folder for my recent runs (rSFSTEP2.Feb2020) and it succesfully completed.

**Comment by chaukap** [comment]
@kpalmqui I copied R_programs 1 and 2 from your runs last night, deleted the output, then submitted the job. Did you use the `compare_sbatch.sh` script?

**Comment by kpalmqui** [comment]
@chaukap I used compare_sbatch.sh and sample. sh by embedding them in the relevant folders.

**Comment by kpalmqui** [comment]
@chaukap so no conflicts with our testing activities which is good! :)

**Comment by chaukap** [comment]
@kpalmqui Great! Just making sure that you didn't run into any problems.

**Comment by kpalmqui** [comment]
@chaukap no issues with executing the new shell script.

However, we failed to remember to update the yaxis limits for the phenological activity figures. All of the Figures I generated last night for phenological activity are mostly useless (see below). The rest of the Figures look good.

![sagebrush_19-27_graph](https://user-images.githubusercontent.com/7769797/75801444-2603cb00-5d49-11ea-9cf6-f96e11cee0cd.png)

**Comment by chaukap** [comment]
@kpalmqui sorry about that! I just bumped the y limit to 1.2 in commit b3c0cb1

**Comment by kpalmqui** [comment]
@chaukap I regenerated these Figures based on commit https://github.com/DrylandEcology/rSFSTEP2/commit/b3c0cb19a8b34921759999aae3de87b05c65b099 but there are still some issues with the Figures not being visible. Rather than fixing the ylim, can we derive it and set it on the fly using max(phenological activity)?

![a cool grass_19-27_graph](https://user-images.githubusercontent.com/7769797/75886602-7d13a980-5df6-11ea-8e9d-e379081bcdc5.png)

**Comment by chaukap** [comment]
@kpalmqui I just pushed a commit to dynamically set ylim.

**Comment by kpalmqui** [comment]
@chaukap still some slight problems with the legend cutting off the Figures. Would it be possible to dump "sxwphen.hydrid-delta-3mod", which would shorter all the names substantially.

![p cool grass_1-9_graph](https://user-images.githubusercontent.com/7769797/76219115-b16ad980-61eb-11ea-92fb-658a2d64e3e1.png)

**Comment by chaukap** [comment]
@kpalmqui My latest commit should finally resolve this issue. I shortened the legend values significantly and I switched the phenology legend to the upper right side.

**Comment by kpalmqui** [comment]
@chaukap It certaintly did - looks great. I did a set of test runs with 53 climate scenarios and none of the phenological activity Figures are cut off now. Here is an example:

![a cool grass_46-53_graph](https://user-images.githubusercontent.com/7769797/76560329-551bea00-6477-11ea-869a-3c7b4e834c5e.png)

Therefore, I am going to close this issue. Thank you!
