### ISSUE TITLE
Site SQLite databases are labeled according to their R_program folder not their site ID

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#220]
Formerly, the SQLite databases were labeled with their site ID provided in generate_rSFSTEP2_structure.sh. Now they are labeled with the R_program folder number, which is not ideal.

It would be great to retain the site ID in the SQLite database name.

@chaukap

**Comment by chaukap** [comment]
@kpalmqui on it!

**Comment by kpalmqui** [comment]
@chaukap your commit above does seem to resolve the initial issue I described, but I have since discovered that the site column in the SQLite output database is also reflecting the R_program folder and not the site ID.

**Comment by kpalmqui** [comment]
@chaukap looks great. The one remaining issue is the site is labeled as "11.0" instead of 11 in the site column of the SQLite database. Any quick fix for this?
