### ISSUE TITLE
Occasionally covariance values generated and populated in mkv_covar.in are negative

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#32]
Very occasionally, the covariance values between weekly maximum temperatures and weekly minimum temperatures that are generated here and written to mkv_covar.in are negative. These values occur very infrequently for sites and for given weeks. These negative values seem to occur for the weeks during the late summer-early fall (weeks 29-36) and the values are usually less than -0.5. 

A recently added check in SW_Markov.c results in the code failing when these conditions occur.

@dschlaep are small negative covariances (suggesting a weak negative relationship) really impossible here?

**Comment by dschlaep** [comment]
Sorry, yes indeed! Commit https://github.com/DrylandEcology/SOILWAT2/commit/7fbdf6e271c2cea4aa95d673c0380018048b4dcb imposes that `cov(x, y) >= 0` which is incorrect because `cov(x, y) < 0` if y tends to increase when x decreases. I'll fix that now.

**Comment by dschlaep** [comment]
@kpalmqui I believe that I fixed this on SOILWAT2 branch `bugfix_224` with commit https://github.com/DrylandEcology/SOILWAT2/pull/225/commits/879d4b6ffb9413e9fc57cf5d113a2418b06c12ad. Could you please test and confirm that the fix resolves this issue before I merge into SOILWAT2's master? Thanks

**Comment by kpalmqui** [comment]
@dschlaep Thank you Daniel! Yes, commit 879d4b6ffb9413e9fc57cf5d113a2418b06c12ad on bugfix_224 resolves this issue. You can merge into master.

**Comment by dschlaep** [comment]
Great! I merged this fix into SOILWAT2 master (v4.1.4).

**Comment by kpalmqui** [comment]
many thanks!
