### ISSUE TITLE
Validation (and/or modification) of code in StepWat.Wrapper.Code_V3.R to be compatible with new input overhaul code in STEPWAT.Wrapper.MAIN_V3.R

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#35]
Thus far, the overhaul to how inputs are deal with has only been implemented in STEPWAT.Wrapper.MAIN_V3.R. We need to confirm that the downstream code in StepWat.Wrapper.Code_V3.R is still compatible with this new workflow and if not, changes need to be made within StepWat.Wrapper.Code_V3.R. 

Currently, in the master branch in StepWat.Wrapper.Code_V3.R, the relevant species.in, rgroup.in, and soils.in files are copied from the STEPWAT_DIST folder to the relevant place in the STEPWAT2 folder and then the executable is called. We need to look into whether this workflow can still be utilized given the changes in how inputs are handled.

**Comment by kpalmqui** [comment]
- the code in StepWat.Wrapper.Code_V3.R is not compatible with the mean implementation in STEPWAT.Wrapper.MAIN_V3.R. 
- previously each site was run with a single set of species parameters. This is not longer the case - sites can be run with multiple sets of species.in parameters. Thus, the code that deals with species.in files needs to be modified accordingly. I will document more clearly once I have a proposed solution.

**Comment by chaukap** [comment]
@kpalmqui I've been running through the new input_overhaul code to locate the problem and it looks like R is throwing errors when sourcing SoilWatOutput.R. The code reads:
```
tempsw2_daily_slyrs$dist_freq<-dst
tempsw2_daily_slyrs$graz_freq<-graz.freq
tempsw2_daily_slyrs$intensity<-intensity
```
where 
```
tempsw2_daily_slyrs$graz_freq<-graz.freq
```
Is causing the error. dst and intensity are both vectors of length one containing an element from their respective vectors (lists). graz.freq is the entire vector, with grz being the equivalent of dst and intensity.

Should graz.freq be changed to grz where this occurs? I see in master that the code reads the same, but I have never tried running with more that one grazing frequency specified.

Let me know what you think. If you need more clarification let me know. 
Thanks!

**Comment by kpalmqui** [comment]
If you could provide examples of the new graz.freq, grz, dst, and intensity here based on the testing conditions you have set up that would be helpful.

From what I can tell - it does appear that we need to change tempsw2_daily_slyrs$graz_freq<-graz.freq to tempsw2_daily_slyrs$graz_freq<-grz

**Comment by chaukap** [comment]
for the testing I've been doing:
```
> dist.freq
[1]  0 50
> graz.freq
[1] 0 1
> graz_intensity
[1] "lowgraz"
```

where the for loops pull out grz from graz.freq, dst from dist.freq and intensity from graz_intensity.

```
for (dst in dist.freq) {
  for (grz in graz.freq) {
    for(intensity in graz_intensity ){
```

**Comment by chaukap** [comment]
I can commit the change for now and we can see how it works. This seems to be correct since dst and intensity are used in SoilWatOutput.R

**Comment by chaukap** [comment]
See issue #72 for more discussion on this issue.

**Comment by chaukap** [comment]
At this point wrapper.code and wrapper.MAIN are compatible. There are minor bugs to fix, but I am closing this issue because in general the two files do work together.
