### ISSUE TITLE
Merge ReadMe.txt into README.md

### ISSUE THREAD

**Issue by chaukap** [DrylandEcology/rSFSTEP2#39]
The two readme files should be merged together so that the user only has to look in one file to learn how to run the code. The README.md is standard on GitHub so the information from ReadMe.txt should be moved into README.md, then ReadMe.txt should be deleted.

**Comment by kpalmqui** [comment]
Closed by commit 87105a3d06a260e7ce5c78a837daf56ac5fbd627
