### ISSUE TITLE
Database Location in Main.R

### ISSUE THREAD

**Issue by nompatil** [DrylandEcology/rSFSTEP2#43]
Database location has to be manually inserted, if windows OS is used then path contains forward slashes while to execute using Cygwin it should take unix based path which contains backward slashes.

**Comment by kpalmqui** [comment]
@fdpierson can this be closed?

**Comment by fdpierson** [comment]
@kpalmqui Yes it can. I believe this issue is specific to the way the OP ran rSFSTEP2.
