### ISSUE TITLE
Calculate July precipitation and temperature of the driest quarter for determination of cheatgrass relative abundance using equations in Brummer et al. 2016

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#52]
- new calculations of July precipitation (mm) and temperature of the driest quarter (C) from daily weather data for each site/climate scenario are needed
- these variables will be used to derive cheatgrass abundance as implemented in Brummer et al. 2016.

I believe a logical place for these derived calculations to occur is in RSoilWat31.Weather.Data.Query_V2.R, whether the daily weather data is extracted for an individual site for all climate conditions that are requested and saved as an sw_weatherList.

**Comment by dschlaep** [comment]
I suggest to add these additional climate variables to the function `calc_SiteClimate` which already calculates the  climate variables from a daily weather object that are required for the climate-vegetation relationships provided by function `estimate_PotNatVeg_composition`.

**Comment by kpalmqui** [comment]
cdf6300 closes this isssue. July PPT and mean temp of the driest quarter are now available with option do_Cheatgrass_ClimVars = TRUE
