### ISSUE TITLE
Re-calculate Paruelo and Lauenroth functional type relative abundance values for each of the STEPPE functional types 

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#54]
After we calculate functional type relative abundance values on the fly based on current or future climate (see issue #53), we will need to re-scale those values for STEPPE functional types:

- shrub -> sagebrush and non-sagebrush shrubs
- c4 grasses -> c4 grasses
- succulents -> succulents
- forbs -> perennial c3 cool-season forbs, perennial c3 warm-season forbs, annual c3 cool-season forbs, annual c3 warm-season forbs
- c3 grasses -> c3 perennial grasses and c3 annual grasses (cheatgrass) ***

I propose this should be placed in a new .R file called Vegetation.R (or whatever the file name is where this is implemented in rSFSW2).

*** we need to decide how to estimate c3 perennial grass and c3 annual grass relative abundance. Should the values for c3 perennial grass from Paruelo and Lauenroth 1996 just represent c3 perennial grasses or both c3 perennial grasses and c3 annual grasses? How will be fit in to c3 annual grass values derived from Brummer et al. 2016 if the former is true?

**Comment by kpalmqui** [comment]
Update:
1. C3 grass relative abundance calculated from the Paruelo and Lauenroth 1996 equations will equal C3 perennial grass abundance. C3 annual grass relative abundance will be derived from a different equation, see issue #56 for more details.

**Comment by kpalmqui** [comment]
![image](https://user-images.githubusercontent.com/7769797/50653233-d06e3b80-0f56-11e9-988c-be120a0362c1.png)

**Comment by chaukap** [comment]
Commit 771fee1 resolves this issue.
