### ISSUE TITLE
Scale vegetation parameters based on STEPPE functional type relative abundance

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#55]
- once the vegetation parameters we want to scale are finalized (some combination of space, pestab, and eind seems likely), utilize the relative abundance of STEPPE functional types to scale those parameters.
- more detail TBA here after identification of the vegetation parameters to scale is complete.

I propose this should be placed in a new .R file called Vegetation.R (or whatever the file name is where this is implemented in rSFSW2).

**Comment by chaukap** [comment]
@kpalmqui I've been looking at the code after relative abundance is calculated, and I have a few questions.  
Can we assume that all of the rgroups present in the new relVegAbund are present in the rgroup file? If not, we will need to make sure that we only populate the necessary Rgroups. 
Also, just to clarify, for every rgroup entry in relVegAbund (for example all entries under the succulents column) we will need to generate a new Rgroup file, correct?

Thanks!

**Comment by kpalmqui** [comment]
@chaukap you bring up some good questions. 

In regards to: 
> Can we assume that all of the rgroups present in the new relVegAbund are present in the rgroup file? If not, we will need to make sure that we only populate the necessary Rgroups.
**I think in almost all cases we will want to simulate shrubs, perennial grasses, forbs, succulents, and annual grasses. So the answer is yes, but let's discuss briefly**

> Also, just to clarify, for every rgroup entry in relVegAbund (for example all entries under the succulents column) we will need to generate a new Rgroup file, correct?
**That is correct - we need seperate rgroup files for each GCM-RCP-time period combination**

**Comment by chaukap** [comment]
As of 1/23/2019 this functionality is working correctly. Commit be51120 creates a function in Vegetation.R that returns the relative abundances for each functional type. Commit 771fee1 then assigns the relative abundance values to STEPPE functional types after redistributing the relative abundance in the case of two species of the same functional type.
