### ISSUE TITLE
Derive climate-cheatgrass equation using raw data provided in Brummer et al. 2016

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#56]
Brummer et al. 2016 utilize boosted regression trees and the "predict" function to examine relationships between cheatgrass abundance and predictor variables. We need to derive the mathmatical relationship between cheatgrass abundance and climate variables identified in Brummer et al. 2016 as presented in Figures 2 and 3. This will allow us to scale cheatgrass abundance on the fly based on july precipitation and mean temperature of the driest quarter.

**Comment by kpalmqui** [comment]
I first fitted the two most important climate variables that emerged from Brummer et al. 2016.

BRTE~ July PPT + Mean temp of driest quarter --> R2 = 0.306

I am also utilizing stepwise regression to assess whether additional climate variables should be included.

**Comment by kpalmqui** [comment]
UPDATE:

July PPT (precip7) and minimum temperature in February (tmin2) explain more variation in BRTE cover than July PPT and Mean temp of the driest quarter --> R2 = 0.32 vs R2 = 0.27.

EQUATION:
BRTE relative cover = 0.3833499 - 0.004692**precip7** + 0.0019285**tmin2**

**Comment by kpalmqui** [comment]
@dschlaep How difficult would it be to add minimum temperature (degrees C) in February to calc_SiteClimate when do_Cheatgrass_ClimVars = TRUE is specified? If not too difficult, I can create an issue in rSOILWAT2 if you would like.

**Comment by dschlaep** [comment]
@kpalmqui I can do this today. To clarify, is "minimum temperature in February" equal to "bio6 = Min temperature of coldest month"?

However, I am somewhat surprised about the form of equation `BRTE relative cover = a - b* prec7 + c * tmin2`. Based on their Figure 4, the relationship looks highly non-linear; that is, I would have guessed that the equation would more something like a piecewise regression or similar:
> if `prec7 > 10 mm | biovar9 < 18 C`, then `BRTE = 0`
> otherwise, `BRTE = a - b * prec7 + c * biovar9 + d * prec7 * biovar9`

**Comment by kpalmqui** [comment]
@dschlaep thanks!! But hold off on this request temporarily while I double-check

**Comment by kpalmqui** [comment]
The relationship between July PPT and BRTE relative cover is not as simple as Figure 4A suggests:

[BRTErelcover_JulyPPT.pdf](https://github.com/DrylandEcology/rSFSTEP2/files/2669464/BRTErelcover_JulyPPT.pdf)

Quite a few sites have significant BRTE cover with values of July PPT > 10mm. Looking at the raw data, BRTE relcover tends to be very close to 0 in almost all sites that have July PPT > 30mm. 

The relationship between BRTE relcover and minimum temperature in Februrary (tmin2) here:

[BRTErelcover_MinFebruaryTemp.pdf](https://github.com/DrylandEcology/rSFSTEP2/files/2669475/BRTErelcover_MinFebruaryTemp.pdf)

The relationship between BRTE relcover and Mean temperature in the driest quarter is less clear and a little weaker than min temp in February:
[BRTErelcover_MeanTempDriestQ.pdf](https://github.com/DrylandEcology/rSFSTEP2/files/2669480/BRTErelcover_MeanTempDriestQ.pdf)

**A revised option might be:**
if prec7 > 30 mm | tmin2 < -13 C, then BRTE = 0
otherwise, BRTE = a - b * prec7 + c *tmin2 + d * prec7 * tmin2

**Comment by dschlaep** [comment]
Wow, indeed! I guess that I mis-interpreted the error bars in their Fig. 4.

I like your revised option. However, aside from those few cold-dry stray points with cheatgrass in `BRTErelcover_MeanTempDriestQ.pdf`, there seems to be a nice relationship for `biovar9 > 15`? Maybe double check whether including all three predictors would be best?

In any case, it seems that I should go ahead and implement `tmin2` in `rSOILWAT2`'s function `calc_SiteClimate`

**Comment by kpalmqui** [comment]
Will do. I agree on tmin2 - which is minimum temperature in the month of February. Thanks @dschlaep

**Comment by kpalmqui** [comment]
I excluded all sites biovar9 <15, prec7>30, and tmin<-13 (BRTE relcover set to 0). Then fit new linear models that included interactions between biovar9, prec7, and tmin and also just prec7 and tmin. Including biovar9 is not a significant improvement.

R2 with biovar9 = 0.35
R2 without biovar9 = 0.34

Summary Table for Proposed final model 
if prec7 > 30 mm | tmin2 < -13 C, then BRTE = 0
otherwise, BRTE = a - b * prec7 + c *tmin2 + d * prec7 * tmin2

**Comment by dschlaep** [comment]
Hm, my piecewise suggestion increased R2 by only 0.02... :-(

**Comment by dschlaep** [comment]
@kpalmqui I updated `rSOILWAT2` function `sw_Cheatgrass_ClimVar`: it now calculates the mean minimum monthly temperature of the second month of the year:

https://github.com/DrylandEcology/rSOILWAT2/commit/18ad58879622daaeb2c0cad0739f4c5c4392600b

Please note that this is now on branch `feature_fun_from_rSFSW2`. Let me know if there are further issues with this.

**Comment by kpalmqui** [comment]
@dschlaep thank you! That should be all.

**Comment by kpalmqui** [comment]
Proposed equation: 
if prec7 > 30 mm | tmin2 < -13 C,
        BRTE = 0
else, 
        BRTE = 0.6732229 - 0.0254591*prec7 + 0.0538173*tmin2 -0.0021601*prec7*tmin2

**Comment by kpalmqui** [comment]
I have re-opened this issue as many sites are losing cheatgrass from current to future conditions under this implementation and this is unexpected. 

I document the new bug in another issue: #240

**Comment by kpalmqui** [comment]
See thread on #240 for new algorithm for deriving cheatgrass abundance based on July PPT and minimum temperature in February.
