### ISSUE TITLE
Describe what options are available in each input csv file for utilizing fixed or site-specific species, rgroup, and soils inputs

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#57]
- for species, rgroup, and soils inputs, the user can specify a variety of options that will utilize fixed values across all sites, fixed values across some sites, or site-specific values for each site. We need to add additional clarification of this in the code base. This is implemented by setting unique combinations of "Site" and "treatment". 

The three options:
1) for fixed inputs for all sites: set "all" in the Site column and fixed**n** in the treatment column, where **n** is a number that uniquely identifies that set of fixed inputs.
2) for fixed inputs for a subset of sites: set the Site column to **x,y**, where x and y correspond to the site IDs of the subset of sites. Also set a unique fixed**n** in the treatment column.
3) for site-specific inputs: set the site ID for each site you want to run in the Site column and specific in the treatment column.

**Comment by chaukap** [comment]
What should happen if the user forgets to set an input for one site? Should the program check to make sure that all sites have all of the inputs specified before running?

**Comment by kpalmqui** [comment]
The default inputs located in the Inputs folder of STEPWAT2 would you utilized instead. So the code will not break, but this is obviously not ideal. We should add a check that ensure that the number of sites specified in each of the Input csv files matches the number of sites to be simulated.

@chaukap any thoughts on where and how best to implement this?

**Comment by kpalmqui** [comment]
Back to the original point of this issue, we have decided to clarify the input options in two places:

1) Main.R, where the inputs are dealt with
2) In a separate .txt file in the inputs folder that explains how the input csvs work and what the options are. Proposed file name: syntax_inputs.txt

**Comment by chaukap** [comment]
In regards to making sure that every site has input:
In wrapper.code, before calling STEPWAT, there is a call to remove the old species.in file
```
system("rm species.in")
```
This will remove the default species.in file, regardless of whether there is a replacement for it. So, if there are no inputs running STEPWAT will crash. I agree that we should print a warning if this occurs, then let the program break on its own.

**Comment by kpalmqui** [comment]
2. listed above was dealt with by commit 0371df9

**Comment by kpalmqui** [comment]
Closed by commit 2347a4a
