### ISSUE TITLE
Add species identifiers to the name of each output file

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#60]
For each combination of site-climate scenario-fire-grazing-soil that is run in StepWat.Wrapper.Code_V3.R, we create a new file output name or ID to denote the treatments that were used to generate that output file. This is true for the biomass output file, mortality output file, and SOILWAT2 output files.

With issue #59 implemented - we will have the option to run the code for multiple sets of species parameters as well. As such, we need to add a species treatment identifier to the output file names in all places in the StepWat.Wrapper.Code_V3.R where files are written. This will indicate to the user which set of species input parameters were used to generated the output files.

**Comment by chaukap** [comment]
@kpalmqui This should be an easy fix, do you have any preferences on where the species identifier should go? For example between grazing and soil type or somewhere else.

**Comment by kpalmqui** [comment]
- at the end of the file name should be fine.

**Comment by kpalmqui** [comment]
Closed by commit d13a33d
