### ISSUE TITLE
Set Annuals_fraction to non-zero within estimate_PotNat_Veg_Composition call within estimate_STEPWAT_relativeVegAbundance

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#75]
The default for annual grasses (Annuals_Fraction) is 0.0 in estimate_PotNat_Veg_Composition within rSOILWAT2. 

For rSFSTEP2, we propose to calculate Annuals_Fraction from the cheatgrass abundance-climate equation described in Brummer et al. 2016, which will be derived in issue #56. This equation will generate a vector of Annuals_Fraction values for each climate scenario that is requested for the site in question. That vector will then be passed to estimate_PotNatVeg_composition on lines 51 and 76 within estimate_STEPWAT_relativeVegAbundance within rSFSTEP2. For example:

temp_veg <- rSOILWAT2::estimate_PotNatVeg_composition(
        MAP_mm = 10 * temp_clim[["MAP_cm"]], MAT_C = temp_clim[["MAT_C"]],
        mean_monthly_ppt_mm = 10 * temp_clim[["meanMonthlyPPTcm"]],
        mean_monthly_Temp_C = temp_clim[["meanMonthlyTempC"]],
        dailyC4vars = temp_clim[["dailyC4vars"]], **Annuals_Fraction = vector**)

Thus, we will leverage the existing estimate_PotNat_Veg_Composition functionality, but include cheatgrass relative abundance in the re-scaling process. This will ensure no additional changes to estimate_PotNat_Veg_Composition to be compatible with rSFSTEP2 and retain all functionality for rSFSW2.

@chaukap have I missed anything?
@dschlaep does this seem like a reasonable approach to you?

**Comment by dschlaep** [comment]
@kpalmqui the suggestion seems reasonable

**Comment by kpalmqui** [comment]
@dschlaep thanks!

**Comment by kpalmqui** [comment]
Implemented by commit f46d607
