### ISSUE TITLE
Error in { : task 2 failed - "object 'dist.grz' not found"

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#83]
A test run of the input_overhaul branch failed due to the following error:

Error in { : task 2 failed - "object 'dist.grz' not found"

This error was thrown in StepWat.Wrapper.Code_V3.R. A bit confusing as I don't see any place in the code where dist.grz is set. @chaukap

**Comment by chaukap** [comment]
dist.grz has been replaced with the correct variable, dist.graz.flag. This resolves the issue.
