### ISSUE TITLE
Code fails if options "all/fixed1" and "siteID/specific" are turned off

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#85]
The code has been written is such a way that all options are expected:

1) specific treatment only
2) fixed treatement for a subset of sites (1,2 option)
3) fixed treatment for all sites

During some testing, I deleted inputs for two options: (1) Site="all", treatment="fixed1" and (2) Site=1, treatment="specific" and the code failed.

[input_overhaul_log.11.30.18.txt](https://github.com/DrylandEcology/rSFSTEP2/files/2634940/input_overhaul_log.11.30.18.txt)

We need to revisit the code within MAIN.R to ensure that the code is compatible when only 1 option is specified.

**Comment by chaukap** [comment]
This problem wouldn't occur if it were not for the paste lines:
```
treatments_species <- paste("species_",treatments_species, sep="")
treatments_vector_species <- paste("species_",treatments_vector_species, "_vector", sep="")
```
If either treatments_species or treatments_species_vector were empty, they contain "species_" after the paste statement. By wrapping the paste statements in if statements we can prevent this from happening.

**Comment by chaukap** [comment]
The rgroup.in files are generated differently. For rgroup, we will need to resolve this issue in parallel with issue #86 since they both involve the same lines of code.

**Comment by kpalmqui** [comment]
The above commits resolve this issue for the soils and species inputs. The code completes if only the 1,2 option is specified for soils and species inputs.

**Comment by chaukap** [comment]
This issue has been resolved for rgroups in the same way that it has been resolved for species and soils. Once commit 2390a53 is tested we can close this issue.
