### ISSUE TITLE
No grazing treatment within rgroup inputs is being labeled as "lowgraz" instead of "nograz"

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#87]
In the rgroup inputs csv, no fire and no grazing is requested for all sites (Site=all, treatment = fixed1).

However, the rgroup.in files that are generated for these conditions and placed in STEPWAT_DIST are mislabeled as "rgroup.freq0.graz.0.lowgraz.in" instead of "rgroup.freq0.graz.0.nograz.in". 

We need to modify the code in MAIN.R to set this option to "nograz".

**Comment by chaukap** [comment]
This issue is resolved with commit 952d8dc. Grazing intensity if now
If grazing is turned on: The value of the highest grazing intensity.
If grazing is turned off: 0.
