### ISSUE TITLE
Remove dist.graz.freq flag (T,F) from code

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#88]
Currently, we utilize a flag - dist.graz.flag - that specifies whether disturbances are turned off or on.  This is no longer necessary. We now identify all combinations of disturbances and simulate them sequentially.  This flag needs to be removed from three places:

1) Main.R - where the flag is set
2) In Wrapper.Code.R, where there are seperate loops for T and F. 
3) This flag is also utilized in several loop structures and added as a column to the total_ tables in SoilWatOutput.R. All reference to dist.graz.flag can now be removed in this file.

**Comment by chaukap** [comment]
As of commit 14e44c6 dist.graz.flag has been remove entirely from the code.
