### ISSUE TITLE
rgroup files have a variable amount of "." separators

### ISSUE THREAD

**Issue by chaukap** [DrylandEcology/rSFSTEP2#95]
The file names for rgroup inputs are parsed by splitting them on every period. This fails if one of the inputs, grazing intensity, grazing frequency, or disturbance frequency, contain a decimal value. The extra period causes the wrong values to be derived from parsing the string. 
To correct this we need to parse the inputs before writing the file names. For example if the grazing intensity is "0.24" we need to parse the "24" and discard the "0.".

**Comment by kpalmqui** [comment]
I tested and this issue was resolved by commit .6097a48
